#!/bin/sh
#
#   13-install-aegir
#   Install LEMP packages and Aegir. Part of the prov-ec2 script series.
#
#   Copyright (c) 2015 James An <james@jamesan.ca>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

source /usr/local/bin/utility-library
tempfile=$(mktemp)

main() {
  _msg 'Setting up Aegir/LEMP stack...'

  _msg2 'Installing LEMP stack packages...'
  pacman --noconfirm --sync --needed mariadb nginx php-fpm
  pacman --noconfirm --sync --needed --asdeps composer
  #~ echo 'extension=phar.so' >| /etc/php/conf.d/phar.ini
  composer self-update

  _msg2 'Installing TU repo and AUR helpers...'
  [ -z "$(grep quarry /etc/pacman.conf)" ] && {
    sed --in-place '/\[core\]/i\[quarry]\nServer = http://pkgbuild.com/~anatolik/quarry/x86_64\n' /etc/pacman.conf
  }
  pacman --sync --refresh --sysupgrade --noconfirm
  for PACKAGE in package-query yaourt; do
    if pacman -Qi $PACKAGE &>/dev/null; then
      continue
    fi
    curl --location https://aur.archlinux.org/cgit/aur.git/snapshot/$PACKAGE.tar.gz | sudo -Hu cloud-user tar --extract --file - --gzip --directory=/tmp
    pushd /tmp/$PACKAGE
    sudo -Hu cloud-user makepkg --install --syncdeps --noconfirm --needed
    popd
  done

  _msg2 'Installing drush, php 5.6, and byobu...'
  sudo -Hu cloud-user gpg --recv-keys 293D771241515FE8
  sudo -Hu cloud-user gpg --lsign-key 293D771241515FE8
  sudo -Hu cloud-user gpg --recv-keys C2BF0BC433CFC8B3
  sudo -Hu cloud-user gpg --lsign-key C2BF0BC433CFC8B3
  sudo -Hu cloud-user yaourt --noconfirm --sync --needed byobu drush-git php56-fpm php56-gd

  _msg2 'Installing aegir...'
  find /etc/drush -name '*.alias.drushrc.php' -delete
  find /usr/share/webapps/hostmaster/sites ~aegir/platforms/*/sites -mindepth 1 -maxdepth 1 -type d -not \( -name default -or -name all \) -exec rm -rf {} +
  sudo -Hu cloud-user yaourt --noconfirm --sync aegir

  _msg2 'Setting up msmtp and mailcatcher as an SMTP server emulator...'
  sudo -Hu cloud-user yaourt --noconfirm --sync --needed msmtp-mta ruby-mailcatcher
  systemctl enable --now mailcatcher.service mailcatcher-smtp@25.socket
  yes | cp --force /etc/msmtprc.aegir /etc/msmtprc

  _msg 'Generate per-user MySQL credentials and disable all shell password authentication...'
  [ "$(systemctl is-active mysqld.service)" = 'active' ] && systemctl stop mysqld.service
  sleep 3 && pkill mysqld
  [ -d /var/lib/mysql ] && rm --force --recursive /var/lib/mysql
  mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql && systemctl start mysqld.service && sleep 3
  SQL_CMDS=()
  for USERNAME in aegir root; do
      # Create mysql user.
      HOME="$(eval echo ~$USERNAME)"
      FILE="$HOME/.my.cnf"
      PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)"
      SQL_CMDS+=("GRANT ALL PRIVILEGES ON *.* TO '$USERNAME'@'%' IDENTIFIED BY '$PASSWORD' WITH GRANT OPTION;")

      # Save mysql user credentials to user's default mysql config file
      [ -f $FILE ] && rm $FILE
      MY_CNF="[client]\nuser=%USER%\npassword=%PASS%"
      MY_CNF="${MY_CNF/\%USER\%/$USERNAME}"
      echo -e "${MY_CNF/\%PASS\%/$PASSWORD}" >| $tempfile
      install -D --owner=$USERNAME --group=$(id --group --name $USERNAME) $tempfile $FILE
  done
  test -v SQL_CMDS && unset SQL_CMDS[${#SQL_CMDS[@]}-1]
  SQL_CMDS+=(
      "UPDATE mysql.user SET PASSWORD=PASSWORD('$(tail -n1 ~root/.my.cnf | sed 's/^password=//')') WHERE User='root';"
      "DELETE FROM mysql.user WHERE User='';"
      "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
      "DROP DATABASE IF EXISTS test;"
      "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
      "FLUSH PRIVILEGES;"
  )
  mv ~root/.my.cnf{,~}
  mysql --execute="${SQL_CMDS[*]}"
  mv ~root/.my.cnf{~,}

  _msg 'Setting up LEMP stack as dedicated Drupal host and Aegir controller'
  _msg2 'Applying ACL onto Aegir files and folders...'
  paths=(
    /etc/drush
    /var/lib/aegir
    /usr/share/webapps/hostmaster
  )
  setfacl --recursive --modify=g:http:rw- "${paths[@]}"
  find "${paths[@]}" -type d -exec sudo setfacl --modify=g:http:rwx {} +

  _msg2 'Setting up the Aegir frontend, Hostmaster...'
  systemctl start nginx.service
  sudo -Hu aegir drush hostmaster-install --web_group=http --http_service_type=nginx \
        --root=/usr/share/webapps/hostmaster \
        --aegir_db_user=$(sudo -Hu aegir sed --quiet --regexp-extended 's/^user=(.+)$/\1/p' ~aegir/.my.cnf) \
        --aegir_db_pass="$(sudo -Hu aegir sed --quiet --regexp-extended 's/^password=(.+)$/\1/p' ~aegir/.my.cnf)" \
        --client_email=aegir@$(hostname) \
        --aegir_host=$(hostname) aegir.$(hostname) \
        --yes
  systemctl enable --now aegir.target

  _msg 'Set up complete!'
}

# invoke main function if this script is executed as a command
if [ "$CMD" = ${BASH_SOURCE##*/} ]; then
  main "$@"
else
  unset main
fi
