#!/bin/sh
#
#   21-aws-cli-snippets
#
#   Copyright (c) 2015 James An <james@jamesan.ca>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

source /usr/local/bin/utility-library
tempfile=$(mktemp)
hostname=$1
scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

get_instance_ip_addr() {
  echo $(aws ec2 describe-instances --instance-ids $instance-id | jq '.Reservations[0].Instances[0].PublicIpAddress' | tr -d '"')
}

update_host_ip_addr() {
  sudo sed -r -i "s/^\s*[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\s+([-_\.\*a-zA-Z0-9]*$hostname)\$/$ip_addr \1/" /etc/hosts
}

main() {
  _msg 'This script has no side effects. Please see code snippets as function blocks in its contents.'
}

# invoke main function if this script is executed as a command
if [ "$CMD" = ${BASH_SOURCE##*/} ]; then
  main "$@"
else
  unset main
fi
